document.getElementById("img1").onclick=function(){
	document.getElementById("ray").style.color='#33cc33';
}
document.getElementById("img3").onclick=function(){
	document.getElementById("francene").style.color='#33cc33';
}
document.getElementById("img2").onclick=function(){
	document.getElementById("kathy").style.color='red';
}
document.getElementById("img4").onclick=function(){
	document.getElementById("weird").style.color='red';
}